version: "3"
services:
  backend:
    build: ../../backend/undertaker/
    command: go run main.go
    image: undertaker
  nginx:
    build: ./nginx
    ports:
      - 80:80
  nextjs:
    build: ./
