version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - undertaker_frontend
  nextjs:
    build: ./
    networks:
      - frontend

networks:
  frontend:
    name: undertaker_frontend
